---
name: Benchmarks on AMD64
permissions: read-all
on: [ workflow_dispatch,push ]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      CSV_FILE_PREFIX: https://pub-95669c22c66d453c92c62f20aa0c5b57.r2.dev
      BUCKET: github-action
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run script
        run: echo $(uuidgen) > b.csv
#        run: chmod +x ./scripts/benchmark.sh && ./scripts/benchmark.sh
      - name: Get result.csv
        run: |
          RESULT_FILE=b.csv
          OBJECT_NAME="etcd-result-$(date '+%Y%m%d%H%M')-main-$(uuidgen).csv"
          echo "RESULT_FILE=$RESULT_FILE" >> $GITHUB_ENV
          echo "OBJECT_NAME=$OBJECT_NAME" >> $GITHUB_ENV
      - name: cpu mem
        run: lscpu; free -h
      - run: |
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
          cat $RESULT_FILE >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
          echo "[file.csv]($CSV_FILE_PREFIX/$OBJECT_NAME)" >> "$GITHUB_STEP_SUMMARY"
          cat <<EOL >> "$GITHUB_STEP_SUMMARY"
          <hr />
          The table shows the median and 90% confidence interval (CI) summaries for each benchmark comparing the HEAD and the BASE of the pull request, and an A/B comparison under "vs base". The last column shows the statistical p-value with ten runs (n=10).
          The last row has the Geometric Mean (geomean) for the given rows in the table.
          Refer to [benchstat's documentation](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) for more help.
          EOL
      - name: Upload to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: --version
          postCommands: |
            echo "*** post commands ***"
            wrangler r2 object put $BUCKET/$OBJECT_NAME --file=$RESULT_FILE
            echo "******"
