---
name: test
permissions: read-all
on: [ workflow_dispatch,push ]

env:
  CSV_FILE_PREFIX: https://pub-95669c22c66d453c92c62f20aa0c5b57.r2.dev
  BUCKET: github-action
  BASE: main
  PR: issue-17098-separate-raft-log-compact-from-snapshot

jobs:

  benchmark-compare-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'clement2026/etcd'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Load Results
        run: |
          echo 'type,ratio,conn_size,value_size,iter1,iter2,iter3,comment
          PARAM,,,,,,,"key_size=256,key_space_size=65536,backend_size=21474836480,range_limit=100,commit=c9fdc60"
          DATA,4.0000,32,256,1293.1367:326.8060,1285.4174:322.8009,1293.1635:321.3521,' > $BASE.csv
          echo 'type,ratio,conn_size,value_size,iter1,iter2,iter3,comment
          PARAM,,,,,,,"key_size=256,key_space_size=65536,backend_size=21474836480,range_limit=100,commit=c9fdc60"
          DATA,4.0000,32,256,1293.1367:326.8060,1285.4174:322.8009,1293.1635:321.3521,' > $PR.csv
      - name: build rw-heatmaps
        run: go build -C tools/rw-heatmaps
      - name: compare
        run: ./tools/rw-heatmaps/rw-heatmaps $BASE.csv $PR.csv -t ' $BASE vs $PR' -o compare
      - name: ls
        run: ls
      - name: zip
        run: zip -r archive.zip *.csv *.jpg ./scripts/*.sh
      - name: write names to env
        run: |
          DATE=$(date '+%Y%m%d-%H-%M-%S')
          
          BASE_CSV_OBJECT_NAME="etcd-benchmark-$DATE-$BASE.csv"
          PR_CSV_OBJECT_NAME="etcd-benchmark-$DATE-$PR.csv"
          COMPARE_READ_OBJECT_NAME="etcd-benchmark-$DATE_compare_read.jpg"
          COMPARE_WRITE_OBJECT_NAME="etcd-benchmark-$DATE_compare_write.jpg"
          ZIP_OBJECT_NAME="etcd-benchmark-$DATE.zip"
          echo "BASE_CSV_OBJECT_NAME=$BASE_CSV_OBJECT_NAME" >> $GITHUB_ENV
          echo "PR_CSV_OBJECT_NAME=$PR_CSV_OBJECT_NAME" >> $GITHUB_ENV
          echo "COMPARE_READ_OBJECT_NAME=$COMPARE_READ_OBJECT_NAME" >> $GITHUB_ENV
          echo "COMPARE_WRITE_OBJECT_NAME=$COMPARE_WRITE_OBJECT_NAME" >> $GITHUB_ENV
          echo "ZIP_OBJECT_NAME=$ZIP_OBJECT_NAME" >> $GITHUB_ENV
      #      - name: cpu mem
      #        run: lscpu; free -h
      - name: print md
        run: |
          echo -n "[archive.zip]($CSV_FILE_PREFIX/$ZIP_OBJECT_NAME)   " >> "$GITHUB_STEP_SUMMARY"
          echo -n "[$BASE.csv]($CSV_FILE_PREFIX/$BASE_CSV_OBJECT_NAME)   " >> "$GITHUB_STEP_SUMMARY"
          echo "[$PR.csv]($CSV_FILE_PREFIX/$PR_CSV_OBJECT_NAME)" >> "$GITHUB_STEP_SUMMARY"
          echo "![]($CSV_FILE_PREFIX/$COMPARE_READ_OBJECT_NAME)" >> "$GITHUB_STEP_SUMMARY"
          echo "![]($CSV_FILE_PREFIX/$COMPARE_WRITE_OBJECT_NAME)" >> "$GITHUB_STEP_SUMMARY"
          cat <<EOL >> "$GITHUB_STEP_SUMMARY"
          EOL
      - name: Upload to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: --version
          postCommands: |
            echo "*** post commands ***"
            wrangler r2 object put $BUCKET/$BASE_CSV_OBJECT_NAME --file=$BASE.csv
            wrangler r2 object put $BUCKET/$PR_CSV_OBJECT_NAME --file=$PR.csv
            wrangler r2 object put $BUCKET/$COMPARE_READ_OBJECT_NAME --file=compare_read.jpg
            wrangler r2 object put $BUCKET/$COMPARE_WRITE_OBJECT_NAME --file=compare_write.jpg
            wrangler r2 object put $BUCKET/$ZIP_OBJECT_NAME --file=archive.zip
            echo "******"
