---
name: Benchmarks on AMD64
permissions: read-all
on: [ push, workflow_dispatch ]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run script
        run: chmod +x ./scripts/benchmark.sh && ./scripts/benchmark.sh
      - name: ls
        run: ls
      - name: ls 2
        run: ls etcd etcd/tools/rw-heatmaps
      - run: |
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
          cat etcd/tools/rw-heatmaps/result.csv >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
          cat <<EOL >> "$GITHUB_STEP_SUMMARY"
          <hr />
          The table shows the median and 90% confidence interval (CI) summaries for each benchmark comparing the HEAD and the BASE of the pull request, and an A/B comparison under "vs base". The last column shows the statistical p-value with ten runs (n=10).
          The last row has the Geometric Mean (geomean) for the given rows in the table.
          Refer to [benchstat's documentation](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat) for more help.
          EOL
