---
name: template
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
      branch:
        required: true
        type: string
      script:
        required: true
        type: string
    outputs:
      results:
        description: The benchmark results
        value: ${{ jobs.benchmark.outputs.results }}

jobs:
  benchmark:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      results: ${{ steps.run-benchmarks.outputs.results }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'clement2026/etcd'
          ref: ${{ inputs.branch }}
          path: etcd
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: etcd/go.sum
      - name: Run script
        run: chmod +x ./scripts/${{ inputs.script }} && ./scripts/${{ inputs.script }}
      - name: ls -lh
        run: ls -lh etcd/tools/rw-heatmaps/*.csv
      - name: print md
        run: |
          file=$(ls etcd/tools/rw-heatmaps/*.csv | head -n 1)
          cat $file
          echo "\`\`\`csv" >> "$GITHUB_STEP_SUMMARY"
          cat $file >> "$GITHUB_STEP_SUMMARY"
          echo "\`\`\`" >> "$GITHUB_STEP_SUMMARY"
      - name: write results
        id: run-benchmarks
        run: |
          RESULT_FILE=$(ls etcd/tools/rw-heatmaps/*.csv | head -n 1)
          echo results="$(base64 -w0 $RESULT_FILE)" >> "$GITHUB_OUTPUT"
      - name: reboot
        run: sudo reboot
