---
name: Reusable Benchmark Template
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    outputs:
      results:
        description: The benchmark results
        value: ${{ jobs.benchmark.outputs.results }}

jobs:
  benchmark:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.run-benchmarks.outputs.results }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'clement2026/etcd'
          ref: ${{ inputs.branch }}
          path: etcd
      - name: ls
        run:  ls
      - name: ls ..
        run:  ls ..
      - name: show branch
        run:  git --git-dir etcd branch
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run script
        run: chmod +x ../scripts/benchmark.sh && ../scripts/benchmark.sh
      - name: Get result.csv
        id: run-benchmarks
        run: |
          RESULT_FILE=$(ls etcd/tools/rw-heatmaps/*.csv | head -n 1)
          echo results="$(base64 -w0 $RESULT_FILE)" >> "$GITHUB_OUTPUT"
