---
name: Benchmarks on AMD64
permissions: read-all
on: [pull_request]
jobs:
  benchmark-head:
    uses: ./.github/workflows/benchmark-template.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  benchmark-base:
    uses: ./.github/workflows/benchmark-template.yaml
    with:
      ref: ${{ github.event.pull_request.base.sha }}

  benchmark-head-and-base:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          fetch-depth: 0
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - name: Benchmark base
        run: |
          go test -timeout=30m -benchmem -run=NONE -bench=. ./... -count=3 | tee base.txt
      - run: |
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Benchmark head
        run: |
          go test -timeout=30m -benchmem -run=NONE -bench=. ./... -count=3 | tee head.txt
      - name: Compare benchmarks
        run: |
          make install-benchstat
          grep ^Benchmark head.txt > head.out
          grep ^Benchmark base.txt > base.out
          benchstat -format csv -confidence=0.75 base.out head.out 2>/dev/null 1> tmp.csv
          echo "$(head -n1 tmp.csv),,," > result.csv # Add three missing cols from header
          tail -n+2 tmp.csv >> result.csv
          benchstat -confidence=0.75 base.out head.out
      - name: Read CSV
        id: read-csv
        uses: juliangruber/read-file-action@b549046febe0fe86f8cb4f93c24e284433f9ab58 # v1.1.7
        with:
          path: ./result.csv
      - name: Create Markdown Table
        uses: petems/csv-to-md-table-action@401501a2cdf2512164c1be3b70411976a2b838b9 # v4.0.0
        id: csv-table-output
        with:
          csvinput: ${{ steps.read-csv.outputs.content }}
      - run: |
          echo "${{ steps.csv-table-output.outputs.markdown-table }}" >> "$GITHUB_STEP_SUMMARY"
  benchmark-compare:
    name: ci-benchmark-compare
    runs-on: ubuntu-latest
    needs: [benchmark-head, benchmark-base]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - name: Set up Go 1.x
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
        id: go
      - name: Load Results
        run: |
          echo "${{ needs.benchmark-base.outputs.results }}" | base64 -d | grep ^Benchmark > base.txt
          echo "${{ needs.benchmark-head.outputs.results }}" | base64 -d | grep ^Benchmark > head.txt
      - name: Compare benchmarks
        run: |
          make install-benchstat
          benchstat -format csv -confidence=0.75 base.txt head.txt 2>/dev/null 1> tmp.csv
          echo "$(head -n1 tmp.csv),,," > result.csv # Add three missing cols from header
          tail -n+2 tmp.csv >> result.csv
          benchstat -confidence=0.75 base.txt head.txt
      - name: Read CSV
        id: read-csv
        uses: juliangruber/read-file-action@b549046febe0fe86f8cb4f93c24e284433f9ab58 # v1.1.7
        with:
          path: ./result.csv
      - name: Create Markdown Table
        uses: petems/csv-to-md-table-action@401501a2cdf2512164c1be3b70411976a2b838b9 # v4.0.0
        id: csv-table-output
        with:
          csvinput: ${{ steps.read-csv.outputs.content }}
      - run: |
          echo "${{ steps.csv-table-output.outputs.markdown-table }}" >> "$GITHUB_STEP_SUMMARY"
