---
name: Test Action
permissions: read-all
on: [ push ]
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: cpu mem
        run: touch abc.csv
      - name: Upload to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          #          command:  r2 object put github-action/etcd-result-$(date '+%Y%m%d%H%M')-.csv --file=dataset.csv
          command: version
          postCommands: |
            echo "*** post commands ***"
            wrangler r2 object put github-action/etcd-result-abc.csv --file=abc.csv
            echo "******"
#          postCommands: |
#            echo "*** post commands ***"
#            wrangler r2 object put github-action/etcd-result-$(date '+%Y%m%d%H%M')-main-$(uuidgen).csv --file=abc.csv
#            echo "******"
